INSERT INTO questions (region_id, question, hint, difficulty)
VALUES (1, 'What is the capital city of Canada?', null,  'easy'),
(1, 'Alaska is part of what country?', null, 'easy' ),
(1, 'Which is the largest country in North America? (by size)', null, 'easy'),
(1, 'What is the national animal of Canada? ', null, 'easy'),
(1, 'How many countries are part of North America?', null, 'medium'),
(1, 'What is the largest city in North America?', null, 'medium'),
(1, 'The United States of America, Canada and Mexico all share what colours on their flags?', null, 'medium'),
(1, 'Which is the highest Mountain in North America?', 'This mountain is north of the US/Canadian border', 'hard'),
(1, 'Which of these are the tallest waterfall in North America?', 'You can find this fall in a national park', 'hard'),
(1, 'What are the cordilleras?', 'These can be found in North, Central and South America', 'hard'),
(2, 'Which is the biggest country in South America? (by size)', null, 'easy'),
(2, 'Which is the smallest country in South America? (by size)', null, 'easy'),
(2, 'What is the longest river in South America?', null, 'easy'),
(2, 'Which one of these countries is a landlocked country?', null, 'easy'),
(2, 'Which South America country has both a Pacific and Atlantic coast?', null, 'medium'),
(2, 'The most populous city in South America?', null, 'medium'),
(2, 'Which South American country is located in the Northern Hemisphere?', null, 'medium'),
(2, 'Which of these cities has never been capital of Brazil?', 'Paulista Avenue is a popular tourist spot in this city', 'hard'),
(2, 'What is an arepa?', 'It can be served with meats and chesse', 'hard'),
(2, 'In which country would you be in if you were flying over the pre-Colombian Nazca lines?', 'This country is home to the Machu Picchu', 'hard'),
(3, 'Which country is home to the Eifel Tower?', null, 'easy'),
(3, 'Which part of Europe is Scandinavia part of?', null, 'easy'),
(3, 'Which country was divided into East and West between the 1940s and 1990s?', null, 'easy'),
(3, 'Which is the most populous capital city in Europe?', null, 'easy'),
(3, 'What is the most common spoken language in Europe?', null, 'medium'),
(3, 'Which of these countries joined the European Union most recently?', null, 'medium'),
(3, 'Which of these countries does not have a monarchy?', null, 'medium'),
(3, 'Which country has won the most Eurovision titles?', 'This country won 4 out of 5 times in the 1990s', 'hard'),
(3, 'In which of these countries does the Danube not flow?', 'It flows through Central and Southeastern Europe', 'hard'),
(3, 'How long is Icelands Ring Road?', 'Equal to almost 820 miles', 'hard'),
(4, 'Which is Asia''s largest country?', null, 'easy'),
(4, 'What is the name of the highest mountain in Asia?', null, 'easy'),
(4, 'Which country is known as a Country of a Thousand Islands?', null, 'easy'),
(4, 'How many people live in Asia?', null, 'easy'),
(4, 'How many countries are in Asia?', null, 'medium'),
(4, 'Which of these cities lies on the Saigon River?', null, 'medium'),
(4, 'In what country is Sichuan found?', null, 'medium'),
(4, 'What separates China from India?', 'These are also a part of Bhutan, India, Nepal & Pakistan', 'hard'),
(4, 'Which city hosted the 1988 Olympic Games?', 'Hodori, a Siberian tiger, was the offical mascot of the Games', 'hard'),
(4, 'A 25km causeway links Saudi Arabia with which other country?', 'This country is east of Saudi Arabia', 'hard'),
(5, 'Which of these is the smallest county in Africa by area?', null, 'easy'),
(5, 'Which of the following is not in Africa?', null, 'easy'),
(5, 'Africa makes up ____ percent of the world’s total land area.', null, 'easy'),
(5, 'Which of these is the largest African city?', null, 'easy'),
(5, 'Which country is based around the hit Disney Movie of animals trying to go back home in the wild?', null, 'medium'),
(5, 'The Mercato is one of Africa’s largest open-air markets and is located in the city of Addis Ababa. But in which country is it?', null, 'medium'),
(5, 'How many countries does the Nile River flow through?', null, 'medium'),
(5, 'The newest country in Africa is?', 'Juba is the capital city', 'hard'),
(5, 'Pick the current president of an African country? (As of 2021)', 'The right answer is the president of South Africa', 'hard'),
(5, 'Which country was called Upper Volta until 1984?', 'This country name means ''Land of Incorruptible People''', 'hard'),
(6, 'What is the constellation on Australia''s flag?', null, 'easy'),
(6, 'What is Austrailia national animal?', null, 'easy'),
(6, 'What is the only living structure that can be seen from space?', null, 'easy'),
(6, 'How many states are there in Australia?',  null, 'easy'),
(6, 'How many of the world’s top 25 deadliest snakes live in Australia?', null, 'medium'),
(6, 'What 2 native Australian mammals lay eggs?', null, 'medium'),
(6, 'Australia is home to the longest fence in the world. What is it called?', null, 'medium'),
(6, 'How many countries are bigger than Australia by area?', null, 'hard'),
(6, 'How many times did Australia win the Rugby World Cup?', 'They have only reached the finals 3 times', 'hard'),
(6, 'What do you call the Aussie favourite sponge cake cubes dipped in chocolate and rolled in coconut?', 'The treat is actually from New Zealand and was originally called a ''Wellington''', 'hard')
