DROP TABLE IF EXISTS games CASCADE;

CREATE TABLE games (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  -- name VARCHAR(255) NOT NULL,
  score VARCHAR(255) NOT NULL
);